// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC.Admin
{
    public class ContentController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ApproveContent = "ApproveContent";
                public readonly string ApproveContentList = "ApproveContentList";
                public readonly string Create = "Create";
                public readonly string Delete = "Delete";
                public readonly string Details = "Details";
                public readonly string Edit = "Edit";
                public readonly string ListPublishedContent = "ListPublishedContent";
                public readonly string ListRejected = "ListRejected";
                public readonly string ListWaiting = "ListWaiting";
                public readonly string ListWrited = "ListWrited";
                public readonly string PublishedContent = "PublishedContent";
                public readonly string Publishing = "Publishing";
                public readonly string Rejected = "Rejected";
                public readonly string RePublish = "RePublish";
                public readonly string Waiting = "Waiting";
                public readonly string Writed = "Writed";
            }
            public readonly string ApproveContent = "~/Areas/Admin/Views/Content/ApproveContent.cshtml";
            public readonly string ApproveContentList = "~/Areas/Admin/Views/Content/ApproveContentList.cshtml";
            public readonly string Create = "~/Areas/Admin/Views/Content/Create.cshtml";
            public readonly string Delete = "~/Areas/Admin/Views/Content/Delete.cshtml";
            public readonly string Details = "~/Areas/Admin/Views/Content/Details.cshtml";
            public readonly string Edit = "~/Areas/Admin/Views/Content/Edit.cshtml";
            public readonly string ListPublishedContent = "~/Areas/Admin/Views/Content/ListPublishedContent.cshtml";
            public readonly string ListRejected = "~/Areas/Admin/Views/Content/ListRejected.cshtml";
            public readonly string ListWaiting = "~/Areas/Admin/Views/Content/ListWaiting.cshtml";
            public readonly string ListWrited = "~/Areas/Admin/Views/Content/ListWrited.cshtml";
            public readonly string PublishedContent = "~/Areas/Admin/Views/Content/PublishedContent.cshtml";
            public readonly string Publishing = "~/Areas/Admin/Views/Content/Publishing.cshtml";
            public readonly string Rejected = "~/Areas/Admin/Views/Content/Rejected.cshtml";
            public readonly string RePublish = "~/Areas/Admin/Views/Content/RePublish.cshtml";
            public readonly string Waiting = "~/Areas/Admin/Views/Content/Waiting.cshtml";
            public readonly string Writed = "~/Areas/Admin/Views/Content/Writed.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
