// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC.Admin
{
    public class ProductController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AddProductMedia = "AddProductMedia";
                public readonly string Create = "Create";
                public readonly string CreateProductAds = "CreateProductAds";
                public readonly string CreateProductVersion = "CreateProductVersion";
                public readonly string DeleteProductAds = "DeleteProductAds";
                public readonly string DeleteProductVersion = "DeleteProductVersion";
                public readonly string DetailProductAds = "DetailProductAds";
                public readonly string EditProductAds = "EditProductAds";
                public readonly string Index = "Index";
                public readonly string List = "List";
                public readonly string ListAd = "ListAd";
                public readonly string ManageProductVersion = "ManageProductVersion";
                public readonly string PausePublishProductAds = "PausePublishProductAds";
                public readonly string ProductAds = "ProductAds";
                public readonly string ProductMedia = "ProductMedia";
                public readonly string ProductVersion = "ProductVersion";
                public readonly string ProductVersionDetails = "ProductVersionDetails";
                public readonly string PublishProductAds = "PublishProductAds";
                public readonly string Update = "Update";
                public readonly string UpdateGeneralInfo = "UpdateGeneralInfo";
                public readonly string UpdateProductVersion = "UpdateProductVersion";
            }
            public readonly string AddProductMedia = "~/Areas/Admin/Views/Product/AddProductMedia.cshtml";
            public readonly string Create = "~/Areas/Admin/Views/Product/Create.cshtml";
            public readonly string CreateProductAds = "~/Areas/Admin/Views/Product/CreateProductAds.cshtml";
            public readonly string CreateProductVersion = "~/Areas/Admin/Views/Product/CreateProductVersion.cshtml";
            public readonly string DeleteProductAds = "~/Areas/Admin/Views/Product/DeleteProductAds.cshtml";
            public readonly string DeleteProductVersion = "~/Areas/Admin/Views/Product/DeleteProductVersion.cshtml";
            public readonly string DetailProductAds = "~/Areas/Admin/Views/Product/DetailProductAds.cshtml";
            public readonly string EditProductAds = "~/Areas/Admin/Views/Product/EditProductAds.cshtml";
            public readonly string Index = "~/Areas/Admin/Views/Product/Index.cshtml";
            public readonly string List = "~/Areas/Admin/Views/Product/List.cshtml";
            public readonly string ListAd = "~/Areas/Admin/Views/Product/ListAd.cshtml";
            public readonly string ManageProductVersion = "~/Areas/Admin/Views/Product/ManageProductVersion.cshtml";
            public readonly string PausePublishProductAds = "~/Areas/Admin/Views/Product/PausePublishProductAds.cshtml";
            public readonly string ProductAds = "~/Areas/Admin/Views/Product/ProductAds.cshtml";
            public readonly string ProductMedia = "~/Areas/Admin/Views/Product/ProductMedia.cshtml";
            public readonly string ProductVersion = "~/Areas/Admin/Views/Product/ProductVersion.cshtml";
            public readonly string ProductVersionDetails = "~/Areas/Admin/Views/Product/ProductVersionDetails.cshtml";
            public readonly string PublishProductAds = "~/Areas/Admin/Views/Product/PublishProductAds.cshtml";
            public readonly string Update = "~/Areas/Admin/Views/Product/Update.cshtml";
            public readonly string UpdateGeneralInfo = "~/Areas/Admin/Views/Product/UpdateGeneralInfo.cshtml";
            public readonly string UpdateProductVersion = "~/Areas/Admin/Views/Product/UpdateProductVersion.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
