// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC.Admin
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Layout = "_Layout";
                public readonly string _LoginLayout = "_LoginLayout";
                public readonly string Error = "Error";
            }
            public readonly string _Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
            public readonly string _LoginLayout = "~/Areas/Admin/Views/Shared/_LoginLayout.cshtml";
            public readonly string Error = "~/Areas/Admin/Views/Shared/Error.cshtml";
            static readonly _DisplayTemplatesClass s_DisplayTemplates = new _DisplayTemplatesClass();
            public _DisplayTemplatesClass DisplayTemplates { get { return s_DisplayTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _DisplayTemplatesClass
            {
                public readonly string AdPublishViewModel = "AdPublishViewModel";
                public readonly string AdViewModel = "AdViewModel";
                public readonly string AgencyViewModel = "AgencyViewModel";
                public readonly string AreaViewModel = "AreaViewModel";
                public readonly string BankAccountItemViewModel = "BankAccountItemViewModel";
                public readonly string BrandViewModel = "BrandViewModel";
                public readonly string CityViewModel = "CityViewModel";
                public readonly string ContentViewModel = "ContentViewModel";
                public readonly string FeedBackViewModel = "FeedBackViewModel";
                public readonly string GroupViewModel = "GroupViewModel";
                public readonly string LinkViewModel = "LinkViewModel";
                public readonly string ProductAdsPublishViewModel = "ProductAdsPublishViewModel";
                public readonly string ProductAdsViewModel = "ProductAdsViewModel";
                public readonly string ProductGroupViewModel = "ProductGroupViewModel";
                public readonly string ProductVersionMediaViewModel = "ProductVersionMediaViewModel";
                public readonly string ProductVersionViewModel = "ProductVersionViewModel";
            }
            static readonly _EditorTemplatesClass s_EditorTemplates = new _EditorTemplatesClass();
            public _EditorTemplatesClass EditorTemplates { get { return s_EditorTemplates; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _EditorTemplatesClass
            {
                public readonly string AdPublishViewModel = "AdPublishViewModel";
                public readonly string AdViewModel = "AdViewModel";
                public readonly string AgencyViewModel = "AgencyViewModel";
                public readonly string AreaViewModel = "AreaViewModel";
                public readonly string BrandViewModel = "BrandViewModel";
                public readonly string CityViewModel = "CityViewModel";
                public readonly string ContentViewModel = "ContentViewModel";
                public readonly string DiscountInfoViewModel = "DiscountInfoViewModel";
                public readonly string GroupViewModel = "GroupViewModel";
                public readonly string LinkViewModel = "LinkViewModel";
                public readonly string MenuOverviewViewModel = "MenuOverviewViewModel";
                public readonly string MenuViewModel = "MenuViewModel";
                public readonly string ProductAdsPublishViewModel = "ProductAdsPublishViewModel";
                public readonly string ProductAdsViewModel = "ProductAdsViewModel";
                public readonly string ProductGeneralInfo = "ProductGeneralInfo";
                public readonly string ProductGroupViewModel = "ProductGroupViewModel";
                public readonly string ProductVersionMediaViewModel = "ProductVersionMediaViewModel";
                public readonly string ProductVersionViewModel = "ProductVersionViewModel";
                public readonly string PublishingContentViewModel = "PublishingContentViewModel";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
