// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC.Admin
{
    public class AccountController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string AccountList = "AccountList";
                public readonly string ChangePassword = "ChangePassword";
                public readonly string Create = "Create";
                public readonly string Delete = "Delete";
                public readonly string Detail = "Detail";
                public readonly string ForgotPassword = "ForgotPassword";
                public readonly string ForgotPasswordConfirmation = "ForgotPasswordConfirmation";
                public readonly string Index = "Index";
                public readonly string Login = "Login";
                public readonly string NumberOfContent = "NumberOfContent";
                public readonly string NumberOfContentList = "NumberOfContentList";
                public readonly string ResetPassword = "ResetPassword";
                public readonly string ResetPasswordConfirmation = "ResetPasswordConfirmation";
                public readonly string Update = "Update";
            }
            public readonly string AccountList = "~/Areas/Admin/Views/Account/AccountList.cshtml";
            public readonly string ChangePassword = "~/Areas/Admin/Views/Account/ChangePassword.cshtml";
            public readonly string Create = "~/Areas/Admin/Views/Account/Create.cshtml";
            public readonly string Delete = "~/Areas/Admin/Views/Account/Delete.cshtml";
            public readonly string Detail = "~/Areas/Admin/Views/Account/Detail.cshtml";
            public readonly string ForgotPassword = "~/Areas/Admin/Views/Account/ForgotPassword.cshtml";
            public readonly string ForgotPasswordConfirmation = "~/Areas/Admin/Views/Account/ForgotPasswordConfirmation.cshtml";
            public readonly string Index = "~/Areas/Admin/Views/Account/Index.cshtml";
            public readonly string Login = "~/Areas/Admin/Views/Account/Login.cshtml";
            public readonly string NumberOfContent = "~/Areas/Admin/Views/Account/NumberOfContent.cshtml";
            public readonly string NumberOfContentList = "~/Areas/Admin/Views/Account/NumberOfContentList.cshtml";
            public readonly string ResetPassword = "~/Areas/Admin/Views/Account/ResetPassword.cshtml";
            public readonly string ResetPasswordConfirmation = "~/Areas/Admin/Views/Account/ResetPasswordConfirmation.cshtml";
            public readonly string Update = "~/Areas/Admin/Views/Account/Update.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
