// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Frontend.Controllers
{
    public partial class ComponentController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ComponentController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Header()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Header);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult MainMenu()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.MainMenu);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult Footer()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.Footer);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult DoesEmailAdsExist()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DoesEmailAdsExist);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SignupNewsletter()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SignupNewsletter);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Display()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Display);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetPartnerLinks()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPartnerLinks);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetContentForGroupID()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetContentForGroupID);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SocialContact()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SocialContact);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetChildGroup()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetChildGroup);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetProductForProductGroupID()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetProductForProductGroupID);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetAllProduct()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllProduct);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult ProductCategory()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.ProductCategory);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ComponentController Actions { get { return MVC.Component; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Component";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Component";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Header = "Header";
            public readonly string MainMenu = "MainMenu";
            public readonly string Footer = "Footer";
            public readonly string DoesEmailAdsExist = "DoesEmailAdsExist";
            public readonly string SignupNewsletter = "SignupNewsletter";
            public readonly string GoogleAnalytics = "GoogleAnalytics";
            public readonly string HeaderScript = "HeaderScript";
            public readonly string BodyScript = "BodyScript";
            public readonly string PartialContact = "PartialContact";
            public readonly string PartialContact_Footer = "PartialContact_Footer";
            public readonly string Display = "Display";
            public readonly string GetPartnerLinks = "GetPartnerLinks";
            public readonly string GetContentForGroupID = "GetContentForGroupID";
            public readonly string ListTagPartial = "ListTagPartial";
            public readonly string SocialContact = "SocialContact";
            public readonly string CopyRight = "CopyRight";
            public readonly string GetChildGroup = "GetChildGroup";
            public readonly string GetProductForProductGroupID = "GetProductForProductGroupID";
            public readonly string GetAllProduct = "GetAllProduct";
            public readonly string ProductCategory = "ProductCategory";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Header = "Header";
            public const string MainMenu = "MainMenu";
            public const string Footer = "Footer";
            public const string DoesEmailAdsExist = "DoesEmailAdsExist";
            public const string SignupNewsletter = "SignupNewsletter";
            public const string GoogleAnalytics = "GoogleAnalytics";
            public const string HeaderScript = "HeaderScript";
            public const string BodyScript = "BodyScript";
            public const string PartialContact = "PartialContact";
            public const string PartialContact_Footer = "PartialContact_Footer";
            public const string Display = "Display";
            public const string GetPartnerLinks = "GetPartnerLinks";
            public const string GetContentForGroupID = "GetContentForGroupID";
            public const string ListTagPartial = "ListTagPartial";
            public const string SocialContact = "SocialContact";
            public const string CopyRight = "CopyRight";
            public const string GetChildGroup = "GetChildGroup";
            public const string GetProductForProductGroupID = "GetProductForProductGroupID";
            public const string GetAllProduct = "GetAllProduct";
            public const string ProductCategory = "ProductCategory";
        }


        static readonly ActionParamsClass_Header s_params_Header = new ActionParamsClass_Header();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Header HeaderParams { get { return s_params_Header; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Header
        {
            public readonly string lang = "lang";
        }
        static readonly ActionParamsClass_MainMenu s_params_MainMenu = new ActionParamsClass_MainMenu();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MainMenu MainMenuParams { get { return s_params_MainMenu; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MainMenu
        {
            public readonly string lang = "lang";
        }
        static readonly ActionParamsClass_Footer s_params_Footer = new ActionParamsClass_Footer();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Footer FooterParams { get { return s_params_Footer; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Footer
        {
            public readonly string lang = "lang";
        }
        static readonly ActionParamsClass_DoesEmailAdsExist s_params_DoesEmailAdsExist = new ActionParamsClass_DoesEmailAdsExist();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DoesEmailAdsExist DoesEmailAdsExistParams { get { return s_params_DoesEmailAdsExist; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DoesEmailAdsExist
        {
            public readonly string email = "email";
        }
        static readonly ActionParamsClass_SignupNewsletter s_params_SignupNewsletter = new ActionParamsClass_SignupNewsletter();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SignupNewsletter SignupNewsletterParams { get { return s_params_SignupNewsletter; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SignupNewsletter
        {
            public readonly string email = "email";
        }
        static readonly ActionParamsClass_PartialContact s_params_PartialContact = new ActionParamsClass_PartialContact();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PartialContact PartialContactParams { get { return s_params_PartialContact; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PartialContact
        {
            public readonly string viewName = "viewName";
        }
        static readonly ActionParamsClass_Display s_params_Display = new ActionParamsClass_Display();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Display DisplayParams { get { return s_params_Display; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Display
        {
            public readonly string position = "position";
            public readonly string viewName = "viewName";
        }
        static readonly ActionParamsClass_GetPartnerLinks s_params_GetPartnerLinks = new ActionParamsClass_GetPartnerLinks();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPartnerLinks GetPartnerLinksParams { get { return s_params_GetPartnerLinks; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPartnerLinks
        {
            public readonly string viewName = "viewName";
            public readonly string component = "component";
        }
        static readonly ActionParamsClass_GetContentForGroupID s_params_GetContentForGroupID = new ActionParamsClass_GetContentForGroupID();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetContentForGroupID GetContentForGroupIDParams { get { return s_params_GetContentForGroupID; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetContentForGroupID
        {
            public readonly string viewName = "viewName";
            public readonly string component = "component";
            public readonly string order = "order";
            public readonly string getTopGroupInfo = "getTopGroupInfo";
            public readonly string defaultname = "defaultname";
            public readonly string notInclude = "notInclude";
        }
        static readonly ActionParamsClass_ListTagPartial s_params_ListTagPartial = new ActionParamsClass_ListTagPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListTagPartial ListTagPartialParams { get { return s_params_ListTagPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListTagPartial
        {
            public readonly string viewName = "viewName";
            public readonly string groupId = "groupId";
        }
        static readonly ActionParamsClass_SocialContact s_params_SocialContact = new ActionParamsClass_SocialContact();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SocialContact SocialContactParams { get { return s_params_SocialContact; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SocialContact
        {
            public readonly string viewName = "viewName";
            public readonly string ContentID = "ContentID";
        }
        static readonly ActionParamsClass_GetChildGroup s_params_GetChildGroup = new ActionParamsClass_GetChildGroup();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetChildGroup GetChildGroupParams { get { return s_params_GetChildGroup; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetChildGroup
        {
            public readonly string id = "id";
            public readonly string viewName = "viewName";
            public readonly string countItem = "countItem";
            public readonly string getAllChildGroup = "getAllChildGroup";
            public readonly string getProductChildGroup = "getProductChildGroup";
        }
        static readonly ActionParamsClass_GetProductForProductGroupID s_params_GetProductForProductGroupID = new ActionParamsClass_GetProductForProductGroupID();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetProductForProductGroupID GetProductForProductGroupIDParams { get { return s_params_GetProductForProductGroupID; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetProductForProductGroupID
        {
            public readonly string viewName = "viewName";
            public readonly string component = "component";
            public readonly string order = "order";
        }
        static readonly ActionParamsClass_GetAllProduct s_params_GetAllProduct = new ActionParamsClass_GetAllProduct();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetAllProduct GetAllProductParams { get { return s_params_GetAllProduct; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetAllProduct
        {
            public readonly string viewName = "viewName";
            public readonly string component = "component";
            public readonly string order = "order";
        }
        static readonly ActionParamsClass_ProductCategory s_params_ProductCategory = new ActionParamsClass_ProductCategory();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ProductCategory ProductCategoryParams { get { return s_params_ProductCategory; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ProductCategory
        {
            public readonly string productGroup = "productGroup";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Footer = "Footer";
                public readonly string GoogleAnalytics = "GoogleAnalytics";
                public readonly string Header = "Header";
                public readonly string MainMenu = "MainMenu";
                public readonly string SubMenuMobile = "SubMenuMobile";
            }
            public readonly string Footer = "~/Views/Component/Footer.cshtml";
            public readonly string GoogleAnalytics = "~/Views/Component/GoogleAnalytics.cshtml";
            public readonly string Header = "~/Views/Component/Header.cshtml";
            public readonly string MainMenu = "~/Views/Component/MainMenu.cshtml";
            public readonly string SubMenuMobile = "~/Views/Component/SubMenuMobile.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ComponentController : Frontend.Controllers.ComponentController
    {
        public T4MVC_ComponentController() : base(Dummy.Instance) { }

        [NonAction]
        partial void HeaderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string lang);

        [NonAction]
        public override System.Web.Mvc.ActionResult Header(string lang)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Header);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lang", lang);
            HeaderOverride(callInfo, lang);
            return callInfo;
        }

        [NonAction]
        partial void MainMenuOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string lang);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult MainMenu(string lang)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.MainMenu);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lang", lang);
            MainMenuOverride(callInfo, lang);
            return callInfo;
        }

        [NonAction]
        partial void FooterOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string lang);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult Footer(string lang)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.Footer);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lang", lang);
            FooterOverride(callInfo, lang);
            return callInfo;
        }

        [NonAction]
        partial void DoesEmailAdsExistOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string email);

        [NonAction]
        public override System.Web.Mvc.JsonResult DoesEmailAdsExist(string email)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.DoesEmailAdsExist);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "email", email);
            DoesEmailAdsExistOverride(callInfo, email);
            return callInfo;
        }

        [NonAction]
        partial void SignupNewsletterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string email);

        [NonAction]
        public override System.Web.Mvc.ActionResult SignupNewsletter(string email)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SignupNewsletter);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "email", email);
            SignupNewsletterOverride(callInfo, email);
            return callInfo;
        }

        [NonAction]
        partial void GoogleAnalyticsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GoogleAnalytics()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GoogleAnalytics);
            GoogleAnalyticsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void HeaderScriptOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult HeaderScript()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.HeaderScript);
            HeaderScriptOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void BodyScriptOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult BodyScript()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BodyScript);
            BodyScriptOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PartialContactOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string viewName);

        [NonAction]
        public override System.Web.Mvc.ActionResult PartialContact(string viewName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PartialContact);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewName", viewName);
            PartialContactOverride(callInfo, viewName);
            return callInfo;
        }

        [NonAction]
        partial void PartialContact_FooterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult PartialContact_Footer()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PartialContact_Footer);
            PartialContact_FooterOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DisplayOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int position, string viewName);

        [NonAction]
        public override System.Web.Mvc.ActionResult Display(int position, string viewName)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Display);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "position", position);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewName", viewName);
            DisplayOverride(callInfo, position, viewName);
            return callInfo;
        }

        [NonAction]
        partial void GetPartnerLinksOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string viewName, Admin.Infrastructure.Helpers.Component component);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetPartnerLinks(string viewName, Admin.Infrastructure.Helpers.Component component)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPartnerLinks);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewName", viewName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "component", component);
            GetPartnerLinksOverride(callInfo, viewName, component);
            return callInfo;
        }

        [NonAction]
        partial void GetContentForGroupIDOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string viewName, Admin.Infrastructure.Helpers.Component component, Store.Service.Service.DistributionOrder order, bool getTopGroupInfo, string defaultname, int? notInclude);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetContentForGroupID(string viewName, Admin.Infrastructure.Helpers.Component component, Store.Service.Service.DistributionOrder order, bool getTopGroupInfo, string defaultname, int? notInclude)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetContentForGroupID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewName", viewName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "component", component);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "order", order);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "getTopGroupInfo", getTopGroupInfo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "defaultname", defaultname);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "notInclude", notInclude);
            GetContentForGroupIDOverride(callInfo, viewName, component, order, getTopGroupInfo, defaultname, notInclude);
            return callInfo;
        }

        [NonAction]
        partial void ListTagPartialOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string viewName, int? groupId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ListTagPartial(string viewName, int? groupId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ListTagPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewName", viewName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "groupId", groupId);
            ListTagPartialOverride(callInfo, viewName, groupId);
            return callInfo;
        }

        [NonAction]
        partial void SocialContactOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string viewName, int? ContentID);

        [NonAction]
        public override System.Web.Mvc.ActionResult SocialContact(string viewName, int? ContentID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SocialContact);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewName", viewName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ContentID", ContentID);
            SocialContactOverride(callInfo, viewName, ContentID);
            return callInfo;
        }

        [NonAction]
        partial void CopyRightOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult CopyRight()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.CopyRight);
            CopyRightOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetChildGroupOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, string viewName, int? countItem, bool getAllChildGroup, bool getProductChildGroup);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetChildGroup(int id, string viewName, int? countItem, bool getAllChildGroup, bool getProductChildGroup)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetChildGroup);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewName", viewName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "countItem", countItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "getAllChildGroup", getAllChildGroup);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "getProductChildGroup", getProductChildGroup);
            GetChildGroupOverride(callInfo, id, viewName, countItem, getAllChildGroup, getProductChildGroup);
            return callInfo;
        }

        [NonAction]
        partial void GetProductForProductGroupIDOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string viewName, Admin.Infrastructure.Helpers.Component component, Store.Service.ProductServices.ProductSortOrder order, string properties);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetProductForProductGroupID(string viewName, Admin.Infrastructure.Helpers.Component component, Store.Service.ProductServices.ProductSortOrder order, string properties)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetProductForProductGroupID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewName", viewName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "component", component);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "order", order);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "properties", properties);
            GetProductForProductGroupIDOverride(callInfo, viewName, component, order, properties);
            return callInfo;
        }

        [NonAction]
        partial void GetAllProductOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string viewName, Admin.Infrastructure.Helpers.Component component, Store.Service.ProductServices.ProductSortOrder order);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetAllProduct(string viewName, Admin.Infrastructure.Helpers.Component component, Store.Service.ProductServices.ProductSortOrder order)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetAllProduct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewName", viewName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "component", component);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "order", order);
            GetAllProductOverride(callInfo, viewName, component, order);
            return callInfo;
        }

        [NonAction]
        partial void ProductCategoryOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int productGroup);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult ProductCategory(int productGroup)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.ProductCategory);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "productGroup", productGroup);
            ProductCategoryOverride(callInfo, productGroup);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
