// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Frontend.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ChangeLanguage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangeLanguage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Contact()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Contact);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Search()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Search);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetPostedContents()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPostedContents);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetPartnerLinks()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPartnerLinks);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string ChangeLanguage = "ChangeLanguage";
            public readonly string Search = "Search";
            public readonly string GetPostedContents = "GetPostedContents";
            public readonly string GetPartnerLinks = "GetPartnerLinks";
            public readonly string ListTagPartial = "ListTagPartial";
            public readonly string Contact = "Contact";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string ChangeLanguage = "ChangeLanguage";
            public const string Search = "Search";
            public const string GetPostedContents = "GetPostedContents";
            public const string GetPartnerLinks = "GetPartnerLinks";
            public const string ListTagPartial = "ListTagPartial";
        }


        static readonly ActionParamsClass_ChangeLanguage s_params_ChangeLanguage = new ActionParamsClass_ChangeLanguage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangeLanguage ChangeLanguageParams { get { return s_params_ChangeLanguage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangeLanguage
        {
            public readonly string lang = "lang";
            public readonly string returnUrl = "returnUrl";
        }
        static readonly ActionParamsClass_Search s_params_Search = new ActionParamsClass_Search();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Search SearchParams { get { return s_params_Search; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Search
        {
            public readonly string query = "query";
            public readonly string brand = "brand";
            public readonly string order = "order";
            public readonly string page = "page";
            public readonly string itemPerPage = "itemPerPage";
        }
        static readonly ActionParamsClass_GetPostedContents s_params_GetPostedContents = new ActionParamsClass_GetPostedContents();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPostedContents GetPostedContentsParams { get { return s_params_GetPostedContents; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPostedContents
        {
            public readonly string viewName = "viewName";
            public readonly string groupID = "groupID";
            public readonly string countItem = "countItem";
            public readonly string order = "order";
        }
        static readonly ActionParamsClass_GetPartnerLinks s_params_GetPartnerLinks = new ActionParamsClass_GetPartnerLinks();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetPartnerLinks GetPartnerLinksParams { get { return s_params_GetPartnerLinks; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetPartnerLinks
        {
            public readonly string viewName = "viewName";
            public readonly string countItem = "countItem";
        }
        static readonly ActionParamsClass_ListTagPartial s_params_ListTagPartial = new ActionParamsClass_ListTagPartial();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ListTagPartial ListTagPartialParams { get { return s_params_ListTagPartial; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ListTagPartial
        {
            public readonly string viewName = "viewName";
            public readonly string groupId = "groupId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string Search = "Search";
                public readonly string SearchResult = "SearchResult";
            }
            public readonly string Index = "~/Views/Home/Index.cshtml";
            public readonly string Search = "~/Views/Home/Search.cshtml";
            public readonly string SearchResult = "~/Views/Home/SearchResult.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HomeController : Frontend.Controllers.HomeController
    {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ChangeLanguageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string lang, string returnUrl);

        [NonAction]
        public override System.Web.Mvc.ActionResult ChangeLanguage(string lang, string returnUrl)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangeLanguage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lang", lang);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "returnUrl", returnUrl);
            ChangeLanguageOverride(callInfo, lang, returnUrl);
            return callInfo;
        }

        [NonAction]
        partial void SearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string query, int? brand, string order, int page, int? itemPerPage);

        [NonAction]
        public override System.Web.Mvc.ActionResult Search(string query, int? brand, string order, int page, int? itemPerPage)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "query", query);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "brand", brand);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "order", order);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "itemPerPage", itemPerPage);
            SearchOverride(callInfo, query, brand, order, page, itemPerPage);
            return callInfo;
        }

        [NonAction]
        partial void GetPostedContentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string viewName, int groupID, int countItem, Store.Service.Service.DistributionOrder order);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetPostedContents(string viewName, int groupID, int countItem, Store.Service.Service.DistributionOrder order)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPostedContents);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewName", viewName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "groupID", groupID);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "countItem", countItem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "order", order);
            GetPostedContentsOverride(callInfo, viewName, groupID, countItem, order);
            return callInfo;
        }

        [NonAction]
        partial void GetPartnerLinksOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string viewName, int countItem);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetPartnerLinks(string viewName, int countItem)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetPartnerLinks);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewName", viewName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "countItem", countItem);
            GetPartnerLinksOverride(callInfo, viewName, countItem);
            return callInfo;
        }

        [NonAction]
        partial void ListTagPartialOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, string viewName, int? groupId);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult ListTagPartial(string viewName, int? groupId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.ListTagPartial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "viewName", viewName);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "groupId", groupId);
            ListTagPartialOverride(callInfo, viewName, groupId);
            return callInfo;
        }

        [NonAction]
        partial void ContactOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Frontend.Models.ContactViewModel customerContact, bool isContact);

        [NonAction]
        public override System.Web.Mvc.JsonResult Contact(Frontend.Models.ContactViewModel customerContact, bool isContact)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Contact);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "customerContact", customerContact);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isContact", isContact);
            ContactOverride(callInfo, customerContact, isContact);
            return callInfo;
        }
    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
