// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Frontend.Controllers
{
    public partial class LayoutController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected LayoutController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Group()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Group);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutContentTiles()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutContentTiles);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutContentList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutContentList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutContentBlock()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutContentBlock);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutContentTimeline()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutContentTimeline);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutContentFocus()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutContentFocus);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutIntroduction()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutIntroduction);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutNews()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutNews);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutCertificate()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutCertificate);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutProduct()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutProduct);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutGroupTiles()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutGroupTiles);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutGroupList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutGroupList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutGroupBlock()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutGroupBlock);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutGroupWithContentTiles()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutGroupWithContentTiles);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutGroupWithContentList()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutGroupWithContentList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutGroupWithContentBlock()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutGroupWithContentBlock);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutContact()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutContact);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutLibrary()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutLibrary);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutPartner()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutPartner);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LayoutContentDetail()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutContentDetail);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DownloadAttached()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadAttached);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Tag()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Tag);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public LayoutController Actions { get { return MVC.Layout; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Layout";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Layout";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Group = "Group";
            public readonly string LayoutContentTiles = "LayoutContentTiles";
            public readonly string LayoutContentList = "LayoutContentList";
            public readonly string LayoutContentBlock = "LayoutContentBlock";
            public readonly string LayoutContentTimeline = "LayoutContentTimeline";
            public readonly string LayoutContentFocus = "LayoutContentFocus";
            public readonly string LayoutIntroduction = "LayoutIntroduction";
            public readonly string LayoutNews = "LayoutNews";
            public readonly string LayoutCertificate = "LayoutCertificate";
            public readonly string LayoutProduct = "LayoutProduct";
            public readonly string LayoutGroupTiles = "LayoutGroupTiles";
            public readonly string LayoutGroupList = "LayoutGroupList";
            public readonly string LayoutGroupBlock = "LayoutGroupBlock";
            public readonly string LayoutGroupWithContentTiles = "LayoutGroupWithContentTiles";
            public readonly string LayoutGroupWithContentList = "LayoutGroupWithContentList";
            public readonly string LayoutGroupWithContentBlock = "LayoutGroupWithContentBlock";
            public readonly string Search = "Search";
            public readonly string LayoutContact = "LayoutContact";
            public readonly string LayoutLibrary = "LayoutLibrary";
            public readonly string LayoutPartner = "LayoutPartner";
            public readonly string LayoutContentDetail = "LayoutContentDetail";
            public readonly string DownloadAttached = "DownloadAttached";
            public readonly string Tag = "Tag";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Group = "Group";
            public const string LayoutContentTiles = "LayoutContentTiles";
            public const string LayoutContentList = "LayoutContentList";
            public const string LayoutContentBlock = "LayoutContentBlock";
            public const string LayoutContentTimeline = "LayoutContentTimeline";
            public const string LayoutContentFocus = "LayoutContentFocus";
            public const string LayoutIntroduction = "LayoutIntroduction";
            public const string LayoutNews = "LayoutNews";
            public const string LayoutCertificate = "LayoutCertificate";
            public const string LayoutProduct = "LayoutProduct";
            public const string LayoutGroupTiles = "LayoutGroupTiles";
            public const string LayoutGroupList = "LayoutGroupList";
            public const string LayoutGroupBlock = "LayoutGroupBlock";
            public const string LayoutGroupWithContentTiles = "LayoutGroupWithContentTiles";
            public const string LayoutGroupWithContentList = "LayoutGroupWithContentList";
            public const string LayoutGroupWithContentBlock = "LayoutGroupWithContentBlock";
            public const string Search = "Search";
            public const string LayoutContact = "LayoutContact";
            public const string LayoutLibrary = "LayoutLibrary";
            public const string LayoutPartner = "LayoutPartner";
            public const string LayoutContentDetail = "LayoutContentDetail";
            public const string DownloadAttached = "DownloadAttached";
            public const string Tag = "Tag";
        }


        static readonly ActionParamsClass_Group s_params_Group = new ActionParamsClass_Group();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Group GroupParams { get { return s_params_Group; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Group
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_LayoutContentTiles s_params_LayoutContentTiles = new ActionParamsClass_LayoutContentTiles();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutContentTiles LayoutContentTilesParams { get { return s_params_LayoutContentTiles; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutContentTiles
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_LayoutContentList s_params_LayoutContentList = new ActionParamsClass_LayoutContentList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutContentList LayoutContentListParams { get { return s_params_LayoutContentList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutContentList
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_LayoutContentBlock s_params_LayoutContentBlock = new ActionParamsClass_LayoutContentBlock();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutContentBlock LayoutContentBlockParams { get { return s_params_LayoutContentBlock; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutContentBlock
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_LayoutContentTimeline s_params_LayoutContentTimeline = new ActionParamsClass_LayoutContentTimeline();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutContentTimeline LayoutContentTimelineParams { get { return s_params_LayoutContentTimeline; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutContentTimeline
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_LayoutContentFocus s_params_LayoutContentFocus = new ActionParamsClass_LayoutContentFocus();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutContentFocus LayoutContentFocusParams { get { return s_params_LayoutContentFocus; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutContentFocus
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_LayoutIntroduction s_params_LayoutIntroduction = new ActionParamsClass_LayoutIntroduction();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutIntroduction LayoutIntroductionParams { get { return s_params_LayoutIntroduction; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutIntroduction
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_LayoutNews s_params_LayoutNews = new ActionParamsClass_LayoutNews();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutNews LayoutNewsParams { get { return s_params_LayoutNews; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutNews
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_LayoutCertificate s_params_LayoutCertificate = new ActionParamsClass_LayoutCertificate();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutCertificate LayoutCertificateParams { get { return s_params_LayoutCertificate; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutCertificate
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_LayoutProduct s_params_LayoutProduct = new ActionParamsClass_LayoutProduct();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutProduct LayoutProductParams { get { return s_params_LayoutProduct; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutProduct
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_LayoutGroupTiles s_params_LayoutGroupTiles = new ActionParamsClass_LayoutGroupTiles();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutGroupTiles LayoutGroupTilesParams { get { return s_params_LayoutGroupTiles; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutGroupTiles
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_LayoutGroupList s_params_LayoutGroupList = new ActionParamsClass_LayoutGroupList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutGroupList LayoutGroupListParams { get { return s_params_LayoutGroupList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutGroupList
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_LayoutGroupBlock s_params_LayoutGroupBlock = new ActionParamsClass_LayoutGroupBlock();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutGroupBlock LayoutGroupBlockParams { get { return s_params_LayoutGroupBlock; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutGroupBlock
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_LayoutGroupWithContentTiles s_params_LayoutGroupWithContentTiles = new ActionParamsClass_LayoutGroupWithContentTiles();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutGroupWithContentTiles LayoutGroupWithContentTilesParams { get { return s_params_LayoutGroupWithContentTiles; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutGroupWithContentTiles
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_LayoutGroupWithContentList s_params_LayoutGroupWithContentList = new ActionParamsClass_LayoutGroupWithContentList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutGroupWithContentList LayoutGroupWithContentListParams { get { return s_params_LayoutGroupWithContentList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutGroupWithContentList
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_LayoutGroupWithContentBlock s_params_LayoutGroupWithContentBlock = new ActionParamsClass_LayoutGroupWithContentBlock();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutGroupWithContentBlock LayoutGroupWithContentBlockParams { get { return s_params_LayoutGroupWithContentBlock; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutGroupWithContentBlock
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_Search s_params_Search = new ActionParamsClass_Search();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Search SearchParams { get { return s_params_Search; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Search
        {
            public readonly string q = "q";
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_LayoutContact s_params_LayoutContact = new ActionParamsClass_LayoutContact();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutContact LayoutContactParams { get { return s_params_LayoutContact; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutContact
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_LayoutLibrary s_params_LayoutLibrary = new ActionParamsClass_LayoutLibrary();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutLibrary LayoutLibraryParams { get { return s_params_LayoutLibrary; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutLibrary
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_LayoutPartner s_params_LayoutPartner = new ActionParamsClass_LayoutPartner();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutPartner LayoutPartnerParams { get { return s_params_LayoutPartner; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutPartner
        {
            public readonly string group = "group";
        }
        static readonly ActionParamsClass_LayoutContentDetail s_params_LayoutContentDetail = new ActionParamsClass_LayoutContentDetail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LayoutContentDetail LayoutContentDetailParams { get { return s_params_LayoutContentDetail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LayoutContentDetail
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DownloadAttached s_params_DownloadAttached = new ActionParamsClass_DownloadAttached();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DownloadAttached DownloadAttachedParams { get { return s_params_DownloadAttached; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DownloadAttached
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Tag s_params_Tag = new ActionParamsClass_Tag();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Tag TagParams { get { return s_params_Tag; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Tag
        {
            public readonly string id = "id";
            public readonly string page = "page";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string LayoutContact = "LayoutContact";
                public readonly string LayoutIntroduction = "LayoutIntroduction";
                public readonly string LayoutNews = "LayoutNews";
                public readonly string LayoutNewsDetail = "LayoutNewsDetail";
            }
            public readonly string LayoutContact = "~/Views/Layout/LayoutContact.cshtml";
            public readonly string LayoutIntroduction = "~/Views/Layout/LayoutIntroduction.cshtml";
            public readonly string LayoutNews = "~/Views/Layout/LayoutNews.cshtml";
            public readonly string LayoutNewsDetail = "~/Views/Layout/LayoutNewsDetail.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_LayoutController : Frontend.Controllers.LayoutController
    {
        public T4MVC_LayoutController() : base(Dummy.Instance) { }

        [NonAction]
        partial void GroupOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Group(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Group);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GroupOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void LayoutContentTilesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutContentTiles(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutContentTiles);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutContentTilesOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void LayoutContentListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutContentList(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutContentList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutContentListOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void LayoutContentBlockOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutContentBlock(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutContentBlock);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutContentBlockOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void LayoutContentTimelineOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutContentTimeline(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutContentTimeline);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutContentTimelineOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void LayoutContentFocusOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutContentFocus(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutContentFocus);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutContentFocusOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void LayoutIntroductionOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutIntroduction(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutIntroduction);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutIntroductionOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void LayoutNewsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutNews(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutNews);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutNewsOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void LayoutCertificateOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutCertificate(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutCertificate);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutCertificateOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void LayoutProductOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutProduct(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutProduct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutProductOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void LayoutGroupTilesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutGroupTiles(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutGroupTiles);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutGroupTilesOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void LayoutGroupListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutGroupList(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutGroupList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutGroupListOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void LayoutGroupBlockOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutGroupBlock(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutGroupBlock);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutGroupBlockOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void LayoutGroupWithContentTilesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutGroupWithContentTiles(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutGroupWithContentTiles);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutGroupWithContentTilesOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void LayoutGroupWithContentListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutGroupWithContentList(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutGroupWithContentList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutGroupWithContentListOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void LayoutGroupWithContentBlockOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutGroupWithContentBlock(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutGroupWithContentBlock);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutGroupWithContentBlockOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void SearchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string q, int page);

        [NonAction]
        public override System.Web.Mvc.ActionResult Search(string q, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Search);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "q", q);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            SearchOverride(callInfo, q, page);
            return callInfo;
        }

        [NonAction]
        partial void LayoutContactOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutContact(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutContact);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutContactOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void LayoutLibraryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutLibrary(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutLibrary);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutLibraryOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void LayoutPartnerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.GroupViewModel group);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutPartner(Frontend.Models.GroupViewModel group)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutPartner);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "group", group);
            LayoutPartnerOverride(callInfo, group);
            return callInfo;
        }

        [NonAction]
        partial void LayoutContentDetailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult LayoutContentDetail(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LayoutContentDetail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            LayoutContentDetailOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DownloadAttachedOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DownloadAttached(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DownloadAttached);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DownloadAttachedOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void TagOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, int page);

        [NonAction]
        public override System.Web.Mvc.ActionResult Tag(int id, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Tag);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            TagOverride(callInfo, id, page);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
