// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Frontend.Controllers
{
    public partial class ShoppingCartController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ShoppingCartController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddToCart()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddToCart);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult AddToWishlist()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AddToWishlist);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult RemoveFromWishlist()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RemoveFromWishlist);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddToCart_Catalog()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddToCart_Catalog);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult UpdateCart()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UpdateCart);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteAllCart()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAllCart);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ApplyCoupon()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ApplyCoupon);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MyOrders()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyOrders);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ShoppingCartController Actions { get { return MVC.ShoppingCart; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "ShoppingCart";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "ShoppingCart";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string AddToCart = "AddToCart";
            public readonly string AddToWishlist = "AddToWishlist";
            public readonly string RemoveFromWishlist = "RemoveFromWishlist";
            public readonly string AddToCart_Catalog = "AddToCart_Catalog";
            public readonly string UpdateCart = "UpdateCart";
            public readonly string DeleteAllCart = "DeleteAllCart";
            public readonly string List = "List";
            public readonly string EmptyCart = "EmptyCart";
            public readonly string ListJson = "ListJson";
            public readonly string GetCartCount = "GetCartCount";
            public readonly string GetWishlistCount = "GetWishlistCount";
            public readonly string OrderSummary = "OrderSummary";
            public readonly string Checkout = "Checkout";
            public readonly string CheckoutSuccess = "CheckoutSuccess";
            public readonly string ApplyCoupon = "ApplyCoupon";
            public readonly string MyOrders = "MyOrders";
            public readonly string OrderDetails = "OrderDetails";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string AddToCart = "AddToCart";
            public const string AddToWishlist = "AddToWishlist";
            public const string RemoveFromWishlist = "RemoveFromWishlist";
            public const string AddToCart_Catalog = "AddToCart_Catalog";
            public const string UpdateCart = "UpdateCart";
            public const string DeleteAllCart = "DeleteAllCart";
            public const string List = "List";
            public const string EmptyCart = "EmptyCart";
            public const string ListJson = "ListJson";
            public const string GetCartCount = "GetCartCount";
            public const string GetWishlistCount = "GetWishlistCount";
            public const string OrderSummary = "OrderSummary";
            public const string Checkout = "Checkout";
            public const string CheckoutSuccess = "CheckoutSuccess";
            public const string ApplyCoupon = "ApplyCoupon";
            public const string MyOrders = "MyOrders";
            public const string OrderDetails = "OrderDetails";
        }


        static readonly ActionParamsClass_AddToCart s_params_AddToCart = new ActionParamsClass_AddToCart();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddToCart AddToCartParams { get { return s_params_AddToCart; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddToCart
        {
            public readonly string productId = "productId";
            public readonly string properties = "properties";
            public readonly string quantity = "quantity";
        }
        static readonly ActionParamsClass_AddToWishlist s_params_AddToWishlist = new ActionParamsClass_AddToWishlist();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddToWishlist AddToWishlistParams { get { return s_params_AddToWishlist; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddToWishlist
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_RemoveFromWishlist s_params_RemoveFromWishlist = new ActionParamsClass_RemoveFromWishlist();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoveFromWishlist RemoveFromWishlistParams { get { return s_params_RemoveFromWishlist; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoveFromWishlist
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddToCart_Catalog s_params_AddToCart_Catalog = new ActionParamsClass_AddToCart_Catalog();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddToCart_Catalog AddToCart_CatalogParams { get { return s_params_AddToCart_Catalog; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddToCart_Catalog
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_UpdateCart s_params_UpdateCart = new ActionParamsClass_UpdateCart();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateCart UpdateCartParams { get { return s_params_UpdateCart; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateCart
        {
            public readonly string model = "model";
            public readonly string deleteBtn = "deleteBtn";
        }
        static readonly ActionParamsClass_DeleteAllCart s_params_DeleteAllCart = new ActionParamsClass_DeleteAllCart();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteAllCart DeleteAllCartParams { get { return s_params_DeleteAllCart; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteAllCart
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Checkout s_params_Checkout = new ActionParamsClass_Checkout();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Checkout CheckoutParams { get { return s_params_Checkout; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Checkout
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ApplyCoupon s_params_ApplyCoupon = new ActionParamsClass_ApplyCoupon();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ApplyCoupon ApplyCouponParams { get { return s_params_ApplyCoupon; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ApplyCoupon
        {
            public readonly string CouponCode = "CouponCode";
        }
        static readonly ActionParamsClass_MyOrders s_params_MyOrders = new ActionParamsClass_MyOrders();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MyOrders MyOrdersParams { get { return s_params_MyOrders; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MyOrders
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_OrderDetails s_params_OrderDetails = new ActionParamsClass_OrderDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_OrderDetails OrderDetailsParams { get { return s_params_OrderDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_OrderDetails
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Checkout = "Checkout";
                public readonly string EmptyCart = "EmptyCart";
                public readonly string List = "List";
                public readonly string ModalCartDetail = "ModalCartDetail";
                public readonly string OrderSummary = "OrderSummary";
            }
            public readonly string Checkout = "~/Views/ShoppingCart/Checkout.cshtml";
            public readonly string EmptyCart = "~/Views/ShoppingCart/EmptyCart.cshtml";
            public readonly string List = "~/Views/ShoppingCart/List.cshtml";
            public readonly string ModalCartDetail = "~/Views/ShoppingCart/ModalCartDetail.cshtml";
            public readonly string OrderSummary = "~/Views/ShoppingCart/OrderSummary.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ShoppingCartController : Frontend.Controllers.ShoppingCartController
    {
        public T4MVC_ShoppingCartController() : base(Dummy.Instance) { }

        [NonAction]
        partial void AddToCartOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int productId, string[] properties, int quantity);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddToCart(int productId, string[] properties, int quantity)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddToCart);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "productId", productId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "properties", properties);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "quantity", quantity);
            AddToCartOverride(callInfo, productId, properties, quantity);
            return callInfo;
        }

        [NonAction]
        partial void AddToWishlistOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.JsonResult AddToWishlist(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AddToWishlist);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AddToWishlistOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void RemoveFromWishlistOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.JsonResult RemoveFromWishlist(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RemoveFromWishlist);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            RemoveFromWishlistOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddToCart_CatalogOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddToCart_Catalog(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddToCart_Catalog);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AddToCart_CatalogOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void UpdateCartOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Frontend.Models.ShoppingCartViewModel model, int? deleteBtn);

        [NonAction]
        public override System.Web.Mvc.JsonResult UpdateCart(Frontend.Models.ShoppingCartViewModel model, int? deleteBtn)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.UpdateCart);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "deleteBtn", deleteBtn);
            UpdateCartOverride(callInfo, model, deleteBtn);
            return callInfo;
        }

        [NonAction]
        partial void DeleteAllCartOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.ShoppingCartViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteAllCart(Frontend.Models.ShoppingCartViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteAllCart);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            DeleteAllCartOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult List()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.List);
            ListOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void EmptyCartOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult EmptyCart()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EmptyCart);
            EmptyCartOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ListJsonOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult ListJson()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ListJson);
            ListJsonOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetCartCountOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetCartCount()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetCartCount);
            GetCartCountOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetWishlistCountOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Web.Mvc.JsonResult GetWishlistCount()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetWishlistCount);
            GetWishlistCountOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void OrderSummaryOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult OrderSummary()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.OrderSummary);
            OrderSummaryOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CheckoutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Checkout()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Checkout);
            CheckoutOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CheckoutSuccessOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CheckoutSuccess()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CheckoutSuccess);
            CheckoutSuccessOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CheckoutOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Frontend.Models.CheckoutViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Checkout(Frontend.Models.CheckoutViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Checkout);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CheckoutOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ApplyCouponOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string CouponCode);

        [NonAction]
        public override System.Web.Mvc.ActionResult ApplyCoupon(string CouponCode)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ApplyCoupon);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "CouponCode", CouponCode);
            ApplyCouponOverride(callInfo, CouponCode);
            return callInfo;
        }

        [NonAction]
        partial void MyOrdersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult MyOrders(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MyOrders);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            MyOrdersOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void OrderDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult OrderDetails(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OrderDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            OrderDetailsOverride(callInfo, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
